### PR TITLE
Evals

### LINKED ISSUE #122: Collect all evaluation results for current models
We have a [script](https://github.com/nightingal3/llm-pretraining-behaviours/blob/main/metadata/collect_integrated_model_scores.py) to collect hf leaderboard results/eval harness results for models, but we should check to make sure it still works to collect results for all the models in `metadata/model_metadata` (or at least all the models listed under `id` here: https://docs.google.com/spreadsheets/d/1MIrVzM51ryJIMu52CLSe45Ej_HUQajH9Bo-_34r0ADw/edit#gid=1374859561)

- If possible, we may also want to change this script since the way it does things now is a bit ugly -- for context we originally were just looking up huggingface leaderboard results, hence the first search through the leaderboard dataset and then the subprocess call to eval harness.

- [ ] Collect new model results for the models in the sheet using the task groups in `eval_task_groups/reasoning_*.yml`
- [ ] (possibly) change the script to be more consistent, e.g. only using eval harness, and changing "x-shot" to the actual number of ICL examples

### PR DESCRIPTION
**Pull request by lintangsutawika**
## Description

- Add bash script to run evals on list of models and list of tasks.
- [WIP] script to collect such evals for analysis.

## References
- Fixes #122

### CODE REVIEW

**Review by nightingal3 — CHANGES_REQUESTED** [review]
Heya, thanks for working on this! I think we want to change the format to match the scores in this directory to integrate with existing schemas: 

Example:
https://github.com/nightingal3/llm-pretraining-behaviours/blob/main/metadata/model_scores/results_meta-llama_Llama-2-70b-hf.json

JSON schema:
https://github.com/nightingal3/llm-pretraining-behaviours/blob/main/metadata/model_results_schema.json

let me know if you have any questions!

**Comment by lintangsutawika** [comment]
@nightingal3 I think we can merge this for now?

**Review by nightingal3 — APPROVED** [review]
Sounds good, sorry for the late approval! Tests seem to be failing though on some of the new metadata

**Comment by nightingal3** [comment]
actually I saw this error too, it's caused by a test file which I fixed in the last commit here:
https://github.com/nightingal3/llm-pretraining-behaviours/pull/136
so it should be fine to merge after this PR is merged into main

**Pull request merged**
